### PR TITLE
TLSA record support

### PR DESCRIPTION
**Pull request by yzguy**
#35 

Add support for TLSA records

/cc @onny, will need someone to live test this because apparently you need a domain registered with Gandi to use their DNS, which I no longer have

### CODE REVIEW

**Review by ross — APPROVED** [review]
👍 code-wise.

**Comment by onny** [comment]
thank you for this PR, looks promising!
running octodns with the config works now:

config
```
"_25._tcp.mx1":
  - type: TLSA
    certificate_usage: 3
    selector: 1
    matching_type: 1
    certificate_association_data: 'da11449b024adc44810b2112aca75aa21a35e6409b2e4012571343211d605b89'
```

octodns-sync 
```
********************************************************************************
* turbotux.de.
********************************************************************************
* gandi (GandiProvider)
*   Create <TlsaRecord TLSA 3600, _25._tcp.mx1.turbotux.de., ['']> (config)
*   Create <SrvRecord SRV 3600, _autodiscover._tcp.turbotux.de., ['']> (config)
*   Summary: Creates=2, Updates=0, Deletes=0, Existing Records=16
********************************************************************************
```

but the record doesn't get created yet :(
```
$ dnsutils --command dig _25._tcp.mx1.turbotux.de TLSA +short
.
```

**Comment by onny** [comment]
if you would like to try, this is my PAT for the domain "turbotux.de": `a18de57a748af2964749079045eab52842d890a3`

**Comment by yzguy** [comment]
@onny I’ll take a look! There’s gotta be something simple I’m missing

**Comment by yzguy** [comment]
@onny Just did a check, it definitely works as intended. Gandi's nameservers are slow to update so if you query immeadiately it doesn't seem to show the change

```yaml
---
_25._tcp.mx1:
  type: TLSA
  values:
    - certificate_association_data: 'da11449b024adc44810b2112aca75aa21a35e6409b2e4012571343211d605b89'
      certificate_usage: 3
      matching_type: 1
      selector: 1
```

```
-> octodns-sync --config-file=config.yaml
2024-02-18T09:31:40  [4376479104] INFO  Manager __init__: config_file=config.yaml, (octoDNS 1.4.0)
2024-02-18T09:31:40  [4376479104] INFO  Manager _config_executor: max_workers=1
2024-02-18T09:31:40  [4376479104] INFO  Manager _config_include_meta: include_meta=False
2024-02-18T09:31:40  [4376479104] INFO  Manager _config_auto_arpa: auto_arpa=False
2024-02-18T09:31:40  [4376479104] INFO  Manager __init__: global_processors=[]
2024-02-18T09:31:40  [4376479104] INFO  Manager __init__: global_post_processors=[]
2024-02-18T09:31:40  [4376479104] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.4.0)
2024-02-18T09:31:40  [4376479104] INFO  Manager __init__: provider=gandi (octodns_gandi 0.0.2)
2024-02-18T09:31:40  [4376479104] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False, plan_output_fh=<stdout>
2024-02-18T09:31:40  [4376479104] INFO  Manager sync:   zone=turbotux.de.
2024-02-18T09:31:40  [4376479104] INFO  Manager sync:   sources=['config']
2024-02-18T09:31:40  [4376479104] INFO  Manager sync:   targets=['gandi']
2024-02-18T09:31:40  [4376479104] INFO  YamlProvider[config] populate:   found 1 records, exists=False
2024-02-18T09:31:40  [4376479104] INFO  GandiProvider[gandi] plan: desired=turbotux.de.
2024-02-18T09:31:41  [4376479104] INFO  GandiProvider[gandi] populate:   found 0 records, exists=True
2024-02-18T09:31:41  [4376479104] INFO  GandiProvider[gandi] plan:   Creates=1, Updates=0, Deletes=0, Existing Records=0
2024-02-18T09:31:41  [4376479104] INFO  Plan
********************************************************************************
* turbotux.de.
********************************************************************************
* gandi (GandiProvider)
*   Create <TlsaRecord TLSA 3600, _25._tcp.mx1.turbotux.de., [''3 1 ''1 da11449b024adc44810b2112aca75aa21a35e6409b2e4012571343211d605b89'']> (config)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=0
********************************************************************************

-> octodns-sync --config-file=config.yaml --doit
2024-02-18T09:32:07  [4334126464] INFO  Manager __init__: config_file=config.yaml, (octoDNS 1.4.0)
2024-02-18T09:32:07  [4334126464] INFO  Manager _config_executor: max_workers=1
2024-02-18T09:32:07  [4334126464] INFO  Manager _config_include_meta: include_meta=False
2024-02-18T09:32:07  [4334126464] INFO  Manager _config_auto_arpa: auto_arpa=False
2024-02-18T09:32:07  [4334126464] INFO  Manager __init__: global_processors=[]
2024-02-18T09:32:07  [4334126464] INFO  Manager __init__: global_post_processors=[]
2024-02-18T09:32:07  [4334126464] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.4.0)
2024-02-18T09:32:07  [4334126464] INFO  Manager __init__: provider=gandi (octodns_gandi 0.0.2)
2024-02-18T09:32:07  [4334126464] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=False, force=False, plan_output_fh=<stdout>
2024-02-18T09:32:07  [4334126464] INFO  Manager sync:   zone=turbotux.de.
2024-02-18T09:32:07  [4334126464] INFO  Manager sync:   sources=['config']
2024-02-18T09:32:07  [4334126464] INFO  Manager sync:   targets=['gandi']
2024-02-18T09:32:07  [4334126464] INFO  YamlProvider[config] populate:   found 1 records, exists=False
2024-02-18T09:32:07  [4334126464] INFO  GandiProvider[gandi] plan: desired=turbotux.de.
2024-02-18T09:32:08  [4334126464] INFO  GandiProvider[gandi] populate:   found 0 records, exists=True
2024-02-18T09:32:08  [4334126464] INFO  GandiProvider[gandi] plan:   Creates=1, Updates=0, Deletes=0, Existing Records=0
2024-02-18T09:32:08  [4334126464] INFO  Plan
********************************************************************************
* turbotux.de.
********************************************************************************
* gandi (GandiProvider)
*   Create <TlsaRecord TLSA 3600, _25._tcp.mx1.turbotux.de., [''3 1 ''1 da11449b024adc44810b2112aca75aa21a35e6409b2e4012571343211d605b89'']> (config)
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=0
********************************************************************************


2024-02-18T09:32:08  [4334126464] INFO  GandiProvider[gandi] apply: making 1 changes to turbotux.de.
2024-02-18T09:32:09  [4334126464] INFO  Manager sync:   1 total changes

-> octodns-sync --config-file=config.yaml
2024-02-18T09:32:35  [4307387776] INFO  Manager __init__: config_file=config.yaml, (octoDNS 1.4.0)
2024-02-18T09:32:35  [4307387776] INFO  Manager _config_executor: max_workers=1
2024-02-18T09:32:35  [4307387776] INFO  Manager _config_include_meta: include_meta=False
2024-02-18T09:32:35  [4307387776] INFO  Manager _config_auto_arpa: auto_arpa=False
2024-02-18T09:32:35  [4307387776] INFO  Manager __init__: global_processors=[]
2024-02-18T09:32:35  [4307387776] INFO  Manager __init__: global_post_processors=[]
2024-02-18T09:32:35  [4307387776] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.4.0)
2024-02-18T09:32:35  [4307387776] INFO  Manager __init__: provider=gandi (octodns_gandi 0.0.2)
2024-02-18T09:32:35  [4307387776] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False, plan_output_fh=<stdout>
2024-02-18T09:32:35  [4307387776] INFO  Manager sync:   zone=turbotux.de.
2024-02-18T09:32:35  [4307387776] INFO  Manager sync:   sources=['config']
2024-02-18T09:32:35  [4307387776] INFO  Manager sync:   targets=['gandi']
2024-02-18T09:32:35  [4307387776] INFO  YamlProvider[config] populate:   found 1 records, exists=False
2024-02-18T09:32:35  [4307387776] INFO  GandiProvider[gandi] plan: desired=turbotux.de.
2024-02-18T09:32:36  [4307387776] INFO  GandiProvider[gandi] populate:   found 1 records, exists=True
2024-02-18T09:32:36  [4307387776] INFO  GandiProvider[gandi] plan:   No changes
2024-02-18T09:32:36  [4307387776] INFO  Plan
********************************************************************************
No changes were planned
********************************************************************************

-> for ns in $(dig NS turbotux.de +short); do echo "$ns => $(dig TLSA _25._tcp.mx1.turbotux.de @$ns +short)"; done
ns-63-a.gandi.net. => 3 1 1 DA11449B024ADC44810B2112ACA75AA21A35E6409B2E401257134321 1D605B89
ns-230-c.gandi.net. => 3 1 1 DA11449B024ADC44810B2112ACA75AA21A35E6409B2E401257134321 1D605B89
ns-48-b.gandi.net. => 3 1 1 DA11449B024ADC44810B2112ACA75AA21A35E6409B2E401257134321 1D605B89
```

If we change the value to 

```
-> octodns-sync --config-file=config.yaml
2024-02-18T09:35:21  [4333667712] INFO  Manager __init__: config_file=config.yaml, (octoDNS 1.4.0)
2024-02-18T09:35:21  [4333667712] INFO  Manager _config_executor: max_workers=1
2024-02-18T09:35:21  [4333667712] INFO  Manager _config_include_meta: include_meta=False
2024-02-18T09:35:21  [4333667712] INFO  Manager _config_auto_arpa: auto_arpa=False
2024-02-18T09:35:21  [4333667712] INFO  Manager __init__: global_processors=[]
2024-02-18T09:35:21  [4333667712] INFO  Manager __init__: global_post_processors=[]
2024-02-18T09:35:21  [4333667712] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.4.0)
2024-02-18T09:35:21  [4333667712] INFO  Manager __init__: provider=gandi (octodns_gandi 0.0.2)
2024-02-18T09:35:21  [4333667712] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False, plan_output_fh=<stdout>
2024-02-18T09:35:21  [4333667712] INFO  Manager sync:   zone=turbotux.de.
2024-02-18T09:35:21  [4333667712] INFO  Manager sync:   sources=['config']
2024-02-18T09:35:21  [4333667712] INFO  Manager sync:   targets=['gandi']
2024-02-18T09:35:21  [4333667712] INFO  YamlProvider[config] populate:   found 1 records, exists=False
2024-02-18T09:35:21  [4333667712] INFO  GandiProvider[gandi] plan: desired=turbotux.de.
2024-02-18T09:35:22  [4333667712] INFO  GandiProvider[gandi] populate:   found 1 records, exists=True
2024-02-18T09:35:22  [4333667712] INFO  GandiProvider[gandi] plan:   Creates=0, Updates=1, Deletes=0, Existing Records=1
2024-02-18T09:35:22  [4333667712] INFO  Plan
********************************************************************************
* turbotux.de.
********************************************************************************
* gandi (GandiProvider)
*   Update
*     <TlsaRecord TLSA 3600, _25._tcp.mx1.turbotux.de., [''3 1 ''1 da11449b024adc44810b2112aca75aa21a35e6409b2e4012571343211d605b89'']> ->
*     <TlsaRecord TLSA 3600, _25._tcp.mx1.turbotux.de., [''3 1 ''1 c164b2c3f36d068d42a6138e446152f568615f28c69bd96a73e354cac88ed00c'']> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=1
********************************************************************************

-> octodns-sync --config-file=config.yaml --doit
2024-02-18T09:35:26  [4369679744] INFO  Manager __init__: config_file=config.yaml, (octoDNS 1.4.0)
2024-02-18T09:35:26  [4369679744] INFO  Manager _config_executor: max_workers=1
2024-02-18T09:35:26  [4369679744] INFO  Manager _config_include_meta: include_meta=False
2024-02-18T09:35:26  [4369679744] INFO  Manager _config_auto_arpa: auto_arpa=False
2024-02-18T09:35:26  [4369679744] INFO  Manager __init__: global_processors=[]
2024-02-18T09:35:26  [4369679744] INFO  Manager __init__: global_post_processors=[]
2024-02-18T09:35:26  [4369679744] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.4.0)
2024-02-18T09:35:26  [4369679744] INFO  Manager __init__: provider=gandi (octodns_gandi 0.0.2)
2024-02-18T09:35:26  [4369679744] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=False, force=False, plan_output_fh=<stdout>
2024-02-18T09:35:26  [4369679744] INFO  Manager sync:   zone=turbotux.de.
2024-02-18T09:35:26  [4369679744] INFO  Manager sync:   sources=['config']
2024-02-18T09:35:26  [4369679744] INFO  Manager sync:   targets=['gandi']
2024-02-18T09:35:26  [4369679744] INFO  YamlProvider[config] populate:   found 1 records, exists=False
2024-02-18T09:35:26  [4369679744] INFO  GandiProvider[gandi] plan: desired=turbotux.de.
2024-02-18T09:35:26  [4369679744] INFO  GandiProvider[gandi] populate:   found 1 records, exists=True
2024-02-18T09:35:26  [4369679744] INFO  GandiProvider[gandi] plan:   Creates=0, Updates=1, Deletes=0, Existing Records=1
2024-02-18T09:35:26  [4369679744] INFO  Plan
********************************************************************************
* turbotux.de.
********************************************************************************
* gandi (GandiProvider)
*   Update
*     <TlsaRecord TLSA 3600, _25._tcp.mx1.turbotux.de., [''3 1 ''1 da11449b024adc44810b2112aca75aa21a35e6409b2e4012571343211d605b89'']> ->
*     <TlsaRecord TLSA 3600, _25._tcp.mx1.turbotux.de., [''3 1 ''1 c164b2c3f36d068d42a6138e446152f568615f28c69bd96a73e354cac88ed00c'']> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=1
********************************************************************************


2024-02-18T09:35:26  [4369679744] INFO  GandiProvider[gandi] apply: making 1 changes to turbotux.de.
2024-02-18T09:35:28  [4369679744] INFO  Manager sync:   1 total changes

-> octodns-sync --config-file=config.yaml
2024-02-18T09:35:31  [4309583232] INFO  Manager __init__: config_file=config.yaml, (octoDNS 1.4.0)
2024-02-18T09:35:31  [4309583232] INFO  Manager _config_executor: max_workers=1
2024-02-18T09:35:31  [4309583232] INFO  Manager _config_include_meta: include_meta=False
2024-02-18T09:35:31  [4309583232] INFO  Manager _config_auto_arpa: auto_arpa=False
2024-02-18T09:35:31  [4309583232] INFO  Manager __init__: global_processors=[]
2024-02-18T09:35:31  [4309583232] INFO  Manager __init__: global_post_processors=[]
2024-02-18T09:35:31  [4309583232] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.4.0)
2024-02-18T09:35:31  [4309583232] INFO  Manager __init__: provider=gandi (octodns_gandi 0.0.2)
2024-02-18T09:35:31  [4309583232] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False, plan_output_fh=<stdout>
2024-02-18T09:35:31  [4309583232] INFO  Manager sync:   zone=turbotux.de.
2024-02-18T09:35:31  [4309583232] INFO  Manager sync:   sources=['config']
2024-02-18T09:35:31  [4309583232] INFO  Manager sync:   targets=['gandi']
2024-02-18T09:35:31  [4309583232] INFO  YamlProvider[config] populate:   found 1 records, exists=False
2024-02-18T09:35:31  [4309583232] INFO  GandiProvider[gandi] plan: desired=turbotux.de.
2024-02-18T09:35:32  [4309583232] INFO  GandiProvider[gandi] populate:   found 1 records, exists=True
2024-02-18T09:35:32  [4309583232] INFO  GandiProvider[gandi] plan:   No changes
2024-02-18T09:35:32  [4309583232] INFO  Plan
********************************************************************************
No changes were planned
********************************************************************************

# After about 2 minutes it starts to show the new value

-> for ns in $(dig NS turbotux.de +short); do echo "$ns => $(dig TLSA _25._tcp.mx1.turbotux.de @$ns +short)"; done
ns-230-c.gandi.net. => 3 1 1 C164B2C3F36D068D42A6138E446152F568615F28C69BD96A73E354CA C88ED00C
ns-63-a.gandi.net. => 3 1 1 C164B2C3F36D068D42A6138E446152F568615F28C69BD96A73E354CA C88ED00C
ns-48-b.gandi.net. => 3 1 1 C164B2C3F36D068D42A6138E446152F568615F28C69BD96A73E354CA C88ED00C
```

Additionally we can dump it and get the expected output

```
-> octodns-dump --config-file=config.yaml --output-dir=tmp turbotux.de. gandi
2024-02-18T09:37:18  [4365190528] INFO  Manager __init__: config_file=config.yaml, (octoDNS 1.4.0)
2024-02-18T09:37:18  [4365190528] INFO  Manager _config_executor: max_workers=1
2024-02-18T09:37:18  [4365190528] INFO  Manager _config_include_meta: include_meta=False
2024-02-18T09:37:18  [4365190528] INFO  Manager _config_auto_arpa: auto_arpa=False
2024-02-18T09:37:18  [4365190528] INFO  Manager __init__: global_processors=[]
2024-02-18T09:37:18  [4365190528] INFO  Manager __init__: global_post_processors=[]
2024-02-18T09:37:18  [4365190528] INFO  Manager __init__: provider=config (octodns.provider.yaml 1.4.0)
2024-02-18T09:37:18  [4365190528] INFO  Manager __init__: provider=gandi (octodns_gandi 0.0.2)
2024-02-18T09:37:18  [4365190528] INFO  Manager dump: zone=turbotux.de., output_dir=tmp, output_provider=None, lenient=False, split=False, sources=['gandi']
2024-02-18T09:37:18  [4365190528] INFO  Manager dump: using custom YamlProvider
2024-02-18T09:37:18  [4365190528] INFO  GandiProvider[gandi] populate:   found 1 records, exists=True
2024-02-18T09:37:18  [4365190528] INFO  YamlProvider[dump] plan: desired=turbotux.de.
2024-02-18T09:37:18  [4365190528] WARNING YamlProvider[dump] root NS record supported, but no record is configured for turbotux.de.
2024-02-18T09:37:18  [4365190528] INFO  YamlProvider[dump] plan:   Creates=1, Updates=0, Deletes=0, Existing Records=0
2024-02-18T09:37:18  [4365190528] INFO  YamlProvider[dump] apply: making 1 changes to turbotux.de.

-> cat tmp/turbotux.de.yaml
---
_25._tcp.mx1:
  type: TLSA
  value:
    certificate_association_data: c164b2c3f36d068d42a6138e446152f568615f28c69bd96a73e354cac88ed00c
    certificate_usage: 3
    matching_type: 1
    selector: 1
```    

Give it a try with the above config, should work

**Comment by onny** [comment]
The config you provided works for me, thank you!

**Pull request merged**
